In [100]:
# IMPORT LIBRARY
import pandas as pd
import numpy as np
import keras
import tensorflow as tf
from keras.layers import Dense
from keras import Sequential
import matplotlib.pyplot as plt

%matplotlib inline

In [146]:
# IMPORT DATASET
dataset = pd.read_csv("Dataset/tinggi_badan.csv",sep=";")
dataset

tinggi_ayah  berat_ayah  tinggi_ibu  berat_ibu gender  tinggi_anak
0           170          80         155         45      L          175
1           166          70         150         55      P          160
2           165          80         149         55      P          160
3           176          66         165         65      L          177
4           183          78         170         67      P          170
5           167          67         150         54      L          175
6           189          90         165         67      P          170
7           157          60         155         73      P          160
8           177          80         150         55      P          155
9           175          76         155         56      L          178
10          172          65         165         73      L          174
11          160          65         145         46      P          146
12          156          53         150         65      L          160
13          157          70         154         65      L          170
14          180         100         164         67      L          184
15          179          77         155         68      P          165
16          167          78         165         76      P          160
17          166          60         171         77      P          160
18          178          90         165         78      P          169
19          165          78         168         70      P          165
20          190          80         173         60      L          205
21          176          76         155         65      P          160
22          174          80         156         55      L          177
23          174          80         165         76      P          166
24          178          68         150         54      P          160
25          160          80         150         65      L          170

In [175]:
# INISIASI INPUT & OUTPUT
x = dataset.loc[:,["tinggi_ayah","berat_ayah","tinggi_ibu","berat_ibu","gender"]]
y = dataset["tinggi_anak"]
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
x["gender"] = le.fit_transform(x["gender"])

In [176]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
column_sels = ["tinggi_ayah","berat_ayah","tinggi_ibu","berat_ibu","gender"]
x = x.loc[:,column_sels]
y = dataset['tinggi_anak']
x = pd.DataFrame(data=min_max_scaler.fit_transform(x), columns=column_sels)

In [177]:
x = x.values
y = y.values

In [178]:
x

array([[0.41176471, 0.57446809, 0.35714286, 0.        , 0.        ],
       [0.29411765, 0.36170213, 0.17857143, 0.3030303 , 1.        ],
       [0.26470588, 0.57446809, 0.14285714, 0.3030303 , 1.        ],
       [0.58823529, 0.27659574, 0.71428571, 0.60606061, 0.        ],
       [0.79411765, 0.53191489, 0.89285714, 0.66666667, 1.        ],
       [0.32352941, 0.29787234, 0.17857143, 0.27272727, 0.        ],
       [0.97058824, 0.78723404, 0.71428571, 0.66666667, 1.        ],
       [0.02941176, 0.14893617, 0.35714286, 0.84848485, 1.        ],
       [0.61764706, 0.57446809, 0.17857143, 0.3030303 , 1.        ],
       [0.55882353, 0.4893617 , 0.35714286, 0.33333333, 0.        ],
       [0.47058824, 0.25531915, 0.71428571, 0.84848485, 0.        ],
       [0.11764706, 0.25531915, 0.        , 0.03030303, 1.        ],
       [0.        , 0.        , 0.17857143, 0.60606061, 0.        ],
       [0.02941176, 0.36170213, 0.32142857, 0.60606061, 0.        ],
       [0.70588235, 1.        , 0.

In [179]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=32)

In [180]:
X_train

array([[0.29411765, 0.14893617, 0.92857143, 0.96969697, 1.        ],
       [0.61764706, 0.57446809, 0.17857143, 0.3030303 , 1.        ],
       [0.        , 0.        , 0.17857143, 0.60606061, 0.        ],
       [0.26470588, 0.57446809, 0.14285714, 0.3030303 , 1.        ],
       [0.02941176, 0.36170213, 0.32142857, 0.60606061, 0.        ],
       [0.58823529, 0.4893617 , 0.35714286, 0.60606061, 1.        ],
       [0.29411765, 0.36170213, 0.17857143, 0.3030303 , 1.        ],
       [0.64705882, 0.31914894, 0.17857143, 0.27272727, 1.        ],
       [0.79411765, 0.53191489, 0.89285714, 0.66666667, 1.        ],
       [0.55882353, 0.4893617 , 0.35714286, 0.33333333, 0.        ],
       [0.47058824, 0.25531915, 0.71428571, 0.84848485, 0.        ],
       [0.11764706, 0.57446809, 0.17857143, 0.60606061, 0.        ],
       [0.58823529, 0.27659574, 0.71428571, 0.60606061, 0.        ],
       [0.02941176, 0.14893617, 0.35714286, 0.84848485, 1.        ],
       [0.26470588, 0.53191489, 0.

In [181]:
# # INISIASI ANN (Artificial Neural Network)
# classifier = Sequential()

# # INISIASI INPUT LAYER DAN HIDDEN LAYER SEBANYAK 5 NODE
# classifier.add(Dense(units = 100, kernel_initializer = 'uniform', activation = 'relu', input_dim = 5))

# # PENDAMBAHAN HIDDEN LAYER KEDUA 
# classifier.add(Dense(units = 100, kernel_initializer = 'uniform', activation = 'relu'))

# # PENDAMBAHAN HIDDEN LAYER KETIGA
# classifier.add(Dense(units = 100, kernel_initializer = 'uniform', activation = 'relu'))

# # PENDAMBAHAN HIDDEN LAYER KELIMA
# classifier.add(Dense(units = 15, kernel_initializer = 'uniform', activation = 'relu'))

# # PENAMBAHAN OUTPUT LAYER
# classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'relu'))

regressor = keras.Sequential([
keras.layers.Dense(15, activation=tf.nn.relu, input_shape=[5]),
keras.layers.Dense(12, activation=tf.nn.relu),
keras.layers.Dense(13, activation=tf.nn.relu),
keras.layers.Dense(1, activation=tf.nn.relu)
])

regressor.compile(optimizer='adam',loss='mean_absolute_error')
save_best_val_loss = keras.callbacks.ModelCheckpoint('best_model_val_loss.h5',save_best_only=True,monitor='val_loss',mode='min')
save_best_loss = keras.callbacks.ModelCheckpoint('best_model_loss.h5',save_best_only=True,monitor='loss',mode='min')

In [182]:
history = regressor.fit(X_train,y_train,validation_data=(X_test, y_test),epochs = 10,batch_size = 400,shuffle = True,callbacks = [save_best_val_loss, save_best_loss])

Train on 19 samples, validate on 7 samples
Epoch 1/10
19/19 [==============================] - 2s 119ms/step - loss: 165.0932 - val_loss: 174.8793
Epoch 2/10
19/19 [==============================] - 0s 172us/step - loss: 165.0740 - val_loss: 174.8587
Epoch 3/10
19/19 [==============================] - 0s 227us/step - loss: 165.0573 - val_loss: 174.8367
Epoch 4/10
19/19 [==============================] - 0s 193us/step - loss: 165.0395 - val_loss: 174.8138
Epoch 5/10
19/19 [==============================] - 0s 260us/step - loss: 165.0209 - val_loss: 174.7904
Epoch 6/10
19/19 [==============================] - 0s 137us/step - loss: 165.0018 - val_loss: 174.7656
Epoch 7/10
19/19 [==============================] - 0s 139us/step - loss: 164.9820 - val_loss: 174.7412
Epoch 8/10
19/19 [==============================] - 0s 141us/step - loss: 164.9627 - val_loss: 174.7167
Epoch 9/10
19/19 [==============================] - 0s 145us/step - loss: 164.9429 - val_loss: 174.6920
Epoch 10/10
19/19 [==

In [183]:
# 170	80	155	45	0
tinggi_ayah = 170
berat_ayah = 80
tinggi_ibu = 150
berat_ibu = 45
gender = 0

predict_data = np.array([tinggi_ayah,berat_ayah,tinggi_ibu,berat_ibu,gender]).reshape(1,5)

# classifier.predict()

In [184]:
classifier.predict(X_test)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
np.array()